export const groupType = {
  1: '群组皮肤',
  2: '个人皮肤',
  3: '通用皮肤',
  4: '捐赠皮肤',
  5: 'VIP皮肤',
  6: '其他',
  7: '活动皮肤',
}

export const modelList = [
  {
      "modelId": 1,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]艾儿茜雅(鱼少赞助)",
      "modelNameEn": "elcia",
      "price": 30000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/ub/bot04/elcia/elcia.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/elcia.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 2,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]泳装牛牛(鱼少赞助)",
      "modelNameEn": "nainiu2",
      "price": 30000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/ub/nainiu2/nainiu3_playermodel.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/nainiu2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 3,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]礼服婚纱牛牛(鱼少赞助)",
      "modelNameEn": "nainiu4",
      "price": 30000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/ub/nainiu4/nainiu3_playermodel.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/nainiu4.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 4,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[HLYM]teto(hlym转模)",
      "modelNameEn": "teto",
      "price": 5000,
      "isPermanent": true,
      "groupType": 1,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": true,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/upkk/kimono_teto/kimono_teto.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/teto.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 5,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[HLYM]旗袍gumi(hlym转模)",
      "modelNameEn": "gumi",
      "price": 5000,
      "isPermanent": true,
      "groupType": 1,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/upkk/gumi_china_dress/gumi.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/gumi_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 6,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[HLYM]neru短裙(hlym转模)",
      "modelNameEn": "neru",
      "price": 5000,
      "isPermanent": true,
      "groupType": 1,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/upkk/neru_l/neru_l.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/nenu_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 7,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[HLYM]埃利亚(hlym转模)",
      "modelNameEn": "aliya",
      "price": 5000,
      "isPermanent": true,
      "groupType": 1,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/upkk/aliya/aliya.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/aliya_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 8,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]百可花",
      "modelNameEn": "bkh",
      "price": 1000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/bkh/bkh.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/bkh.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 9,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]符玄",
      "modelNameEn": "fuxuan",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/fuxuan/fuxuan.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/fuxuan.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 10,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]花火",
      "modelNameEn": "huahuo",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/huahuo/huahuo.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/huahuo.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 11,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]花嫁猫诺",
      "modelNameEn": "huajiamaonuo",
      "price": 1000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/huajiamaonuo/huajiamaonuo.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/huajiamaonuo.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 12,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠][懒懒的白兔]恶毒",
      "modelNameEn": "le_malin",
      "price": 1000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/le_malin/le_malin.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/le_malin.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 13,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]凑阿库娅",
      "modelNameEn": "minatoaqua",
      "price": 1000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/minatoaqua/minatoaqua.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/minatoaqua.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 14,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]兔子洞初音未来",
      "modelNameEn": "rabbitholemiku",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/rabbitholemiku/rabbitholemiku.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/rabbitholemiku.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 17,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "Anon",
      "modelNameEn": "anon",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/anon/anon.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/anon.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 18,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "艾莉",
      "modelNameEn": "arya",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/arya/arya.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/arya.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 20,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]阿罗娜",
      "modelNameEn": "arona",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/arona/arona.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/arona.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 21,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]Manuka女警",
      "modelNameEn": "arrested",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/arrested/arrested.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/arrested.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 22,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]戚风StreetGrunge",
      "modelNameEn": "c1",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/c1/c1.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/c1.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 23,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]Kuronyam",
      "modelNameEn": "Kuronyam",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/kuronyam/kuronyam.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/kuronyam.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 24,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]Manuka棉花糖",
      "modelNameEn": "marshmallow",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/marshmallow/marshmallow.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/marshmallow.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 25,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]戚风Rabbit Rangely",
      "modelNameEn": "rabbit",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/rabbit/rabbit.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/rabbit.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 26,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]八十八键",
      "modelNameEn": "sweater",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/sweater/sweater.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/sweater.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 27,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]大凤",
      "modelNameEn": "taihou",
      "price": 1000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/taihou/taihou.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/taihou.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 28,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]风铃",
      "modelNameEn": "tomorrow",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/tomorrow/tomorrow.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/tomorrow.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 29,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]Maya[Obsidian]",
      "modelNameEn": "urban_maya",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/urban_maya/urban_maya.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/urban_maya.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 30,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]九尾VeilofTheFawn",
      "modelNameEn": "veil",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/byd_cat/veil/veil.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/veil.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 32,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]艾雅法拉[泳装]",
      "modelNameEn": "eyjafjalla",
      "price": 1000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/eyjafjalla/eyjafjalla.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/eyjafjalla_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 34,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]怨仇",
      "modelNameEn": "implacable",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/implacable/implacable.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/implacable_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 35,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[体操服]伊洛玛丽(hlym修复版)",
      "modelNameEn": "iochi_mari_gym",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/iochi_mari_gym/iochi_mari_gym.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/iochi_mari_gym_V2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 36,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]「琪花星烛」可莉",
      "modelNameEn": "keli",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/keli/keli.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/keli_V2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 37,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]琪亚娜[崩坏世界的歌姬]",
      "modelNameEn": "kiana_singer",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/kiana_singer/kiana_singer.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/kiana_singer_V2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 39,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "幼灵梦(hlym修复版)",
      "modelNameEn": "lingmeng",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/lingmeng/lingmeng.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/lingmeng_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 41,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]莫拉娜",
      "modelNameEn": "molana",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/molana/molana.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/molana_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 42,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]白色校服弱音",
      "modelNameEn": "haku_school",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/haku_school/haku_school.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/haku_school_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 43,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]夏装希儿",
      "modelNameEn": "xier_summer",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/xier_summer/xier_summer.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/xier_summer_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 48,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]月下誓约-此生永携",
      "modelNameEn": "yuexia_huajia",
      "price": 1500,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/upkk/yuexia_huajia/yuexia_huajia.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/yuexia_huajia_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 50,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]原神胡桃",
      "modelNameEn": "HuTao",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/rho/hutao/hutao.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/hutao_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 51,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]原神安柏",
      "modelNameEn": "amber",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/nozb1/amber_player_model/amber_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/amber_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 52,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]夏洛特",
      "modelNameEn": "charlotte",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/nozb1/charlotte_player_model/charlotte_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/charlotte_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 53,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]海初音",
      "modelNameEn": "miku_sea",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/nozb1/miku_sea_player_model/miku_sea_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/miku_sea_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 54,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]铁道银狼",
      "modelNameEn": "silver_wolf",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/nozb1/silver_wolf_player_model/silver_wolf_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/silver_wolf_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 55,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]初音索尼克",
      "modelNameEn": "sonic_miku",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/nozb1/sonic_miku_player_model/sonic_miku_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/sonic_miku_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 56,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]四系乃",
      "modelNameEn": "yoshino",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/nozb1/yoshino_player_model/yoshino_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/yoshino_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 57,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]大海王星",
      "modelNameEn": "neptune",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 3,
      "modelPath": "characters/models/nozb1/adult_neptune_player_model/adult_neptune_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/neptune_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 58,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]nekopara巧克力",
      "modelNameEn": "chocola",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/chocola_player_model/chocola_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/chocola_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 59,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]封印者(cybernetic)",
      "modelNameEn": "cybernetic",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/cybernetic_closer_player_model/cybernetic_closer_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/cybernetic_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 60,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]原神镀金旅团女性",
      "modelNameEn": "eremitedesert",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/eremitedesert_player_model/eremitedesert_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/eremitedesert_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 61,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]eula",
      "modelNameEn": "eula",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/eula_player_model/eula_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/eula_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 62,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]komo",
      "modelNameEn": "komo",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/komo_player_model/komo_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/komo_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 63,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]雷姆",
      "modelNameEn": "rem",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/zerorem_player_model/zerorem_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/rem_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 64,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]古拉(原皮)",
      "modelNameEn": "gura",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/gawr_gura_player_model/gawr_gura_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/gura_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 65,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]原神九条沙罗",
      "modelNameEn": "kujousara",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/kujousara_player_model/kujousara_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/kujousara_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 66,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]laremicat",
      "modelNameEn": "laremicat",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/laremicat_player_model/laremicat_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/laremicat_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 67,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]nia",
      "modelNameEn": "nia",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 2,
      "modelPath": "characters/models/nozb1/nia_player_model/nia_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/nia_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 68,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "[公共]原神莱欧斯利",
      "modelNameEn": "wriothesley",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": "",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 1,
      "modelPath": "characters/models/nozb1/wriothesley_player_model/wriothesley_player_model.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/wriothesley_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 69,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]索菲亚(浮夸冷心赞助)",
      "modelNameEn": "sophina",
      "price": 50000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/cs2ze/sophina/sophina.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/sophina.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 70,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]婚纱艾儿茜雅(鱼少专属)",
      "modelNameEn": "elcia_personal",
      "price": 99999999,
      "isPermanent": true,
      "groupType": 2,
      "faction": "1",
      "exclusiveTo": "76561198851997954",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/exg/bot04/elcia/elcia.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/elcia_personal.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 73,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]saber_wedding(个人专属皮)",
      "modelNameEn": "saber_wedding_personal",
      "price": 99999999,
      "isPermanent": true,
      "groupType": 2,
      "faction": "2",
      "exclusiveTo": "76561198318054155,76561198272062145",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 6,
      "modelPath": "characters/models/upkk/saber_wedding_dress/saber_wedding_dress_v3.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/saber_wedding_personal.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 74,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]凤凰luka(个人专属皮)",
      "modelNameEn": "luka_red_dress_personal",
      "price": 99999999,
      "isPermanent": true,
      "groupType": 2,
      "faction": "2",
      "exclusiveTo": "76561198318054155,76561198272062145",
      "isArchived": false,
      "hasDiscount": false,
      "quality": 6,
      "modelPath": "characters/models/upkk/luka_red_dress/luka_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/luka_red_dress_personal.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 75,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]洛琪希(小翟赞助)",
      "modelNameEn": "luoqixi",
      "price": 8888,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/exg/chrisan/luoqixi/luoqixi.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/luoqixi.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 76,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[韩服]有栖マナ(hlym转模)",
      "modelNameEn": "mana",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/mana/mana_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/mana.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 77,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[女仆]有栖マナ(hlym转模)",
      "modelNameEn": "mana_maid",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/mana_maid/mana_maid_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/mana_maid.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 78,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "Foxmiko(hlym转模)",
      "modelNameEn": "foxmiko",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/foxmiko/foxmiko_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/foxmiko.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 79,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[舰娘]金刚(hlym转模)",
      "modelNameEn": "kongou_v1",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/kongou_v1/kongou_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/kongou_v1.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 80,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "黑岩射手(hlym转模)",
      "modelNameEn": "black_rock_shooter",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/black_rock_shooter/black_rock_shooter_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/black_shooter_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 81,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "九尾狐(hlym转模)",
      "modelNameEn": "fox_miku",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/fox_miku/fox_miku_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/fox_miku_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 82,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "康娜(hlym转模)",
      "modelNameEn": "kanna",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/kanna/kanna_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/Kanna_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 83,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "琴里(hlym转模)",
      "modelNameEn": "qinli",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/qinli/qinli_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/qinli_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 84,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "夏娜(hlym转模)",
      "modelNameEn": "shana",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/shana/shana_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/shana_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 85,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[韩服]狗妈(hlym转模)",
      "modelNameEn": "kagura_nana_v1",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/kagura_nana_v1/kagura_nana_v1_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/kagura_nana_v1.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 86,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]柴郡猫猫(一堆杠杠赞助)",
      "modelNameEn": "junchai",
      "price": 50000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/hlym/junchai/junchai.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/junchai_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 87,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "csol2校服miyu(hlym转模)",
      "modelNameEn": "miyu_schoolgirl",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/miyu_schoolgirl/miyu_schoolgirl_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/miyu_school_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 88,
      "modelType": 0,
      "categoryId": 1,
      "modelName": "csol2崔智云(hlym转模)",
      "modelNameEn": "choi",
      "price": 0,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 4,
      "modelPath": "characters/models/hlym/choi/choi_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/choi_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 89,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[芒种]洛天依(hlym转模)",
      "modelNameEn": "mzlty",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/mzlty/mzlty_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/mzlty.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 90,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "八重神子(hlym转模)",
      "modelNameEn": "bcsz",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/bcsz/bcsz_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/bcsz.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 91,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "成年芽衣(hlym转模)",
      "modelNameEn": "cnyy",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/cnyy/cnyy_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/cnyy.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 92,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[蝶律]乐正绫(hlym转模)",
      "modelNameEn": "dlyzl",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/dlyzl/dlyzl_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/dlyzl.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 93,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "兰序言和(hlym转模)",
      "modelNameEn": "lxyh",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/lxyh/lxyh_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/lxyh.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 94,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[黑色]旗袍希儿(hlym转模)",
      "modelNameEn": "qpxed",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/qpxed/qpxed_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/qpxed.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 95,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[Re0]艾米莉亚(hlym转模)",
      "modelNameEn": "emilia",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/emilia/emilia_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/emilia.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 96,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[少前]UMP45(hlym转模)",
      "modelNameEn": "ump45_v1",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": true,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/ump45_v1/ump45_v1_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/ump45.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 97,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "Akame(hlym转模)",
      "modelNameEn": "akame_v1",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": true,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/akame_v1/akame_v1_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/akame.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 98,
      "modelType": 2,
      "categoryId": 1,
      "modelName": "[捐赠]莉洛莫伊斯(氢气赞助)",
      "modelNameEn": "liloumois",
      "price": 35000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 7,
      "modelPath": "characters/models/exg/qingqi/liloumois/liloumois.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/liloumois_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 99,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]星乃一歌",
      "modelNameEn": "hoshino_ichika",
      "price": 1000,
      "isPermanent": true,
      "groupType": 4,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/kx/hoshino_ichika/hoshino_ichika.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/hoshino_ichika_v2.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 100,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠][明日方舟]年(hlym转模)",
      "modelNameEn": "year_v3",
      "price": 1500,
      "isPermanent": true,
      "groupType": 3,
      "faction": "1",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/year_v3/year_v3_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/year_v3.png",
      "previewOnline": false,
      "previewType": 2
  },
  {
      "modelId": 101,
      "modelType": 1,
      "categoryId": 1,
      "modelName": "[捐赠]小北方(hlym转模)",
      "modelNameEn": "hoppou",
      "price": 1000,
      "isPermanent": true,
      "groupType": 3,
      "faction": "2",
      "exclusiveTo": null,
      "isArchived": false,
      "hasDiscount": false,
      "quality": 5,
      "modelPath": "characters/models/hlym/hoppou/hoppou_prefab.vmdl",
      "previewUrl": "https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/hoppou.png",
      "previewOnline": false,
      "previewType": 2
  }
]

