export const modelList = [
  {
    modelName: '[捐赠]婚纱艾儿茜雅(鱼少专属)',
    price: 99999999,
    modelId: '70',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/exg/bot04/elcia/elcia.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/elcia_personal.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]saber_wedding(个人专属皮)',
    price: 99999999,
    modelId: '73',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '6',
    modelPath: 'characters/models/upkk/saber_wedding_dress/saber_wedding_dress_v3.vmdl',
    previewUrl:
      'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/saber_wedding_personal.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]凤凰luka(个人专属皮)',
    price: 99999999,
    modelId: '74',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '6',
    modelPath: 'characters/models/upkk/luka_red_dress/luka_prefab.vmdl',
    previewUrl:
      'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/luka_red_dress_personal.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]索菲亚(浮夸冷心赞助)',
    price: 50000,
    modelId: '69',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/cs2ze/sophina/sophina.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/sophina.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]柴郡猫猫(一堆杠杠赞助)',
    price: 50000,
    modelId: '86',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/hlym/junchai/junchai.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/junchai_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]莉洛莫伊斯(氢气赞助)',
    price: 35000,
    modelId: '98',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/exg/qingqi/liloumois/liloumois.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/liloumois_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]艾儿茜雅(鱼少赞助)',
    price: 30000,
    modelId: '1',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/ub/bot04/elcia/elcia.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/elcia.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]泳装牛牛(鱼少赞助)',
    price: 30000,
    modelId: '2',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/ub/nainiu2/nainiu3_playermodel.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/nainiu2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]礼服婚纱牛牛(鱼少赞助)',
    price: 30000,
    modelId: '3',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/ub/nainiu4/nainiu3_playermodel.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/nainiu4.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[捐赠]洛琪希(小翟赞助)',
    price: 8888,
    modelId: '75',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '7',
    modelPath: 'characters/models/exg/chrisan/luoqixi/luoqixi.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/luoqixi.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '2',
    tags: ['捐赠', '个人专属', '专属模型'],
  },
  {
    modelName: '[HLYM]teto(hlym转模)',
    price: 5000,
    modelId: '4',
    isPermanent: 1,
    faction: '1',
    isArchived: 1,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/upkk/kimono_teto/kimono_teto.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/teto.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['HLYM', 'hlym转模'],
  },
  {
    modelName: '[HLYM]旗袍gumi(hlym转模)',
    price: 5000,
    modelId: '5',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/upkk/gumi_china_dress/gumi.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/gumi_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['HLYM', 'hlym转模'],
  },
  {
    modelName: '[HLYM]neru短裙(hlym转模)',
    price: 5000,
    modelId: '6',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/upkk/neru_l/neru_l.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/nenu_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['HLYM', 'hlym转模'],
  },
  {
    modelName: '[HLYM]埃利亚(hlym转模)',
    price: 5000,
    modelId: '7',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/upkk/aliya/aliya.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/aliya_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['HLYM', 'hlym转模'],
  },
  {
    modelName: '[捐赠]符玄',
    price: 1500,
    modelId: '9',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/fuxuan/fuxuan.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/fuxuan.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠'],
  },
  {
    modelName: '[捐赠]花火',
    price: 1500,
    modelId: '10',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/huahuo/huahuo.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/huahuo.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠'],
  },
  {
    modelName: '[捐赠]兔子洞初音未来',
    price: 1500,
    modelId: '14',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/rabbitholemiku/rabbitholemiku.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/rabbitholemiku.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠'],
  },
  {
    modelName: 'Anon',
    price: 1500,
    modelId: '17',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/anon/anon.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/anon.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['普通'],
  },
  {
    modelName: '艾莉',
    price: 1500,
    modelId: '18',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/arya/arya.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/arya.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['普通'],
  },
  {
    modelName: '[捐赠]阿罗娜',
    price: 1500,
    modelId: '20',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/arona/arona.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/arona.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]Manuka女警',
    price: 1500,
    modelId: '21',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/arrested/arrested.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/arrested.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]戚风StreetGrunge',
    price: 1500,
    modelId: '22',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/c1/c1.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/c1.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]Kuronyam',
    price: 1500,
    modelId: '23',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/kuronyam/kuronyam.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/kuronyam.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]Manuka棉花糖',
    price: 1500,
    modelId: '24',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/marshmallow/marshmallow.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/marshmallow.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]戚风Rabbit Rangely',
    price: 1500,
    modelId: '25',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/rabbit/rabbit.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/rabbit.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]八十八键',
    price: 1500,
    modelId: '26',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/sweater/sweater.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/sweater.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]风铃',
    price: 1500,
    modelId: '28',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/tomorrow/tomorrow.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/tomorrow.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]Maya[Obsidian]',
    price: 1500,
    modelId: '29',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/urban_maya/urban_maya.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/urban_maya.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]九尾VeilofTheFawn',
    price: 1500,
    modelId: '30',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/veil/veil.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/veil.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]怨仇',
    price: 1500,
    modelId: '34',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/implacable/implacable.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/implacable_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[体操服]伊洛玛丽(hlym修复版)',
    price: 1500,
    modelId: '35',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/iochi_mari_gym/iochi_mari_gym.vmdl',
    previewUrl:
      'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/iochi_mari_gym_V2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]「琪花星烛」可莉',
    price: 1500,
    modelId: '36',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/keli/keli.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/keli_V2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]琪亚娜[崩坏世界的歌姬]',
    price: 1500,
    modelId: '37',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/kiana_singer/kiana_singer.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/kiana_singer_V2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]莫拉娜',
    price: 1500,
    modelId: '41',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/molana/molana.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/molana_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]白色校服弱音',
    price: 1500,
    modelId: '42',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/haku_school/haku_school.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/haku_school_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]夏装希儿',
    price: 1500,
    modelId: '43',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/xier_summer/xier_summer.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/xier_summer_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]月下誓约-此生永携',
    price: 1500,
    modelId: '48',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/yuexia_huajia/yuexia_huajia.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/yuexia_huajia_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '黑岩射手(hlym转模)',
    price: 1500,
    modelId: '80',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/black_rock_shooter/black_rock_shooter_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/black_shooter_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[韩服]狗妈(hlym转模)',
    price: 1500,
    modelId: '85',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/kagura_nana_v1/kagura_nana_v1_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/kagura_nana_v1.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[芒种]洛天依(hlym转模)',
    price: 1500,
    modelId: '89',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/mzlty/mzlty_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/mzlty.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '八重神子(hlym转模)',
    price: 1500,
    modelId: '90',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/bcsz/bcsz_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/bcsz.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '成年芽衣(hlym转模)',
    price: 1500,
    modelId: '91',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/cnyy/cnyy_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/cnyy.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[蝶律]乐正绫(hlym转模)',
    price: 1500,
    modelId: '92',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/dlyzl/dlyzl_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/dlyzl.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '兰序言和(hlym转模)',
    price: 1500,
    modelId: '93',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/lxyh/lxyh_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/lxyh.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[黑色]旗袍希儿(hlym转模)',
    price: 1500,
    modelId: '94',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/qpxed/qpxed_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/qpxed.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[Re0]艾米莉亚(hlym转模)',
    price: 1500,
    modelId: '95',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/emilia/emilia_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/emilia.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[少前]UMP45(hlym转模)',
    price: 1500,
    modelId: '96',
    isPermanent: 1,
    faction: '1',
    isArchived: 1,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/ump45_v1/ump45_v1_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/ump45.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[捐赠][明日方舟]年(hlym转模)',
    price: 1500,
    modelId: '100',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/year_v3/year_v3_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/year_v3.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[捐赠]百可花',
    price: 1000,
    modelId: '8',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/bkh/bkh.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/bkh.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]花嫁猫诺',
    price: 1000,
    modelId: '11',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/huajiamaonuo/huajiamaonuo.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/huajiamaonuo.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠][懒懒的白兔]恶毒',
    price: 1000,
    modelId: '12',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/le_malin/le_malin.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/le_malin.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]凑阿库娅',
    price: 1000,
    modelId: '13',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/minatoaqua/minatoaqua.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/minatoaqua.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]大凤',
    price: 1000,
    modelId: '27',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/byd_cat/taihou/taihou.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/taihou.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]艾雅法拉[泳装]',
    price: 1000,
    modelId: '32',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/upkk/eyjafjalla/eyjafjalla.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/eyjafjalla_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '幼灵梦(hlym修复版)',
    price: 1000,
    modelId: '39',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/lingmeng/lingmeng.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/lingmeng_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[韩服]有栖マナ(hlym转模)',
    price: 1000,
    modelId: '76',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/mana/mana_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/mana.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[女仆]有栖マナ(hlym转模)',
    price: 1000,
    modelId: '77',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/mana_maid/mana_maid_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/mana_maid.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: 'Foxmiko(hlym转模)',
    price: 1000,
    modelId: '78',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/foxmiko/foxmiko_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/foxmiko.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[舰娘]金刚(hlym转模)',
    price: 1000,
    modelId: '79',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/kongou_v1/kongou_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/kongou_v1.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '九尾狐(hlym转模)',
    price: 1000,
    modelId: '81',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/fox_miku/fox_miku_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/fox_miku_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '康娜(hlym转模)',
    price: 1000,
    modelId: '82',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/kanna/kanna_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/Kanna_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '琴里(hlym转模)',
    price: 1000,
    modelId: '83',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/qinli/qinli_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/qinli_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '夏娜(hlym转模)',
    price: 1000,
    modelId: '84',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/shana/shana_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/shana_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: 'Akame(hlym转模)',
    price: 1000,
    modelId: '97',
    isPermanent: 1,
    faction: '1',
    isArchived: 1,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/akame_v1/akame_v1_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/akame.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[捐赠]星乃一歌',
    price: 1000,
    modelId: '99',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/kx/hoshino_ichika/hoshino_ichika.vmdl',
    previewUrl:
      'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/hoshino_ichika_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通'],
  },
  {
    modelName: '[捐赠]小北方(hlym转模)',
    price: 1000,
    modelId: '101',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '5',
    modelPath: 'characters/models/hlym/hoppou/hoppou_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/hoppou.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '1',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: '[公共]原神胡桃',
    price: 0,
    modelId: '50',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/rho/hutao/hutao.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/hutao_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]原神安柏',
    price: 0,
    modelId: '51',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/nozb1/amber_player_model/amber_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/amber_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]夏洛特',
    price: 0,
    modelId: '52',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/nozb1/charlotte_player_model/charlotte_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/charlotte_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]海初音',
    price: 0,
    modelId: '53',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/nozb1/miku_sea_player_model/miku_sea_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/miku_sea_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]铁道银狼',
    price: 0,
    modelId: '54',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/nozb1/silver_wolf_player_model/silver_wolf_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/silver_wolf_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]初音索尼克',
    price: 0,
    modelId: '55',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/nozb1/sonic_miku_player_model/sonic_miku_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/sonic_miku_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]四系乃',
    price: 0,
    modelId: '56',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/nozb1/yoshino_player_model/yoshino_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/yoshino_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]大海王星',
    price: 0,
    modelId: '57',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '3',
    modelPath: 'characters/models/nozb1/adult_neptune_player_model/adult_neptune_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/neptune_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]nekopara巧克力',
    price: 0,
    modelId: '58',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/chocola_player_model/chocola_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/chocola_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]封印者(cybernetic)',
    price: 0,
    modelId: '59',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath:
      'characters/models/nozb1/cybernetic_closer_player_model/cybernetic_closer_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/cybernetic_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]原神镀金旅团女性',
    price: 0,
    modelId: '60',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/eremitedesert_player_model/eremitedesert_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/eremitedesert_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]eula',
    price: 0,
    modelId: '61',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/eula_player_model/eula_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/eula_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]komo',
    price: 0,
    modelId: '62',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/komo_player_model/komo_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/komo_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]雷姆',
    price: 0,
    modelId: '63',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/zerorem_player_model/zerorem_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/rem_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]古拉(原皮)',
    price: 0,
    modelId: '64',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/gawr_gura_player_model/gawr_gura_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/gura_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]原神九条沙罗',
    price: 0,
    modelId: '65',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/kujousara_player_model/kujousara_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/kujousara_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]laremicat',
    price: 0,
    modelId: '66',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/laremicat_player_model/laremicat_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/laremicat_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]nia',
    price: 0,
    modelId: '67',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '2',
    modelPath: 'characters/models/nozb1/nia_player_model/nia_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/nia_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: '[公共]原神莱欧斯利',
    price: 0,
    modelId: '68',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '1',
    modelPath: 'characters/models/nozb1/wriothesley_player_model/wriothesley_player_model.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/wriothesley_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', '公共'],
  },
  {
    modelName: 'csol2校服miyu(hlym转模)',
    price: 0,
    modelId: '87',
    isPermanent: 1,
    faction: '1',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/miyu_schoolgirl/miyu_schoolgirl_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/T/miyu_school_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
  {
    modelName: 'csol2崔智云(hlym转模)',
    price: 0,
    modelId: '88',
    isPermanent: 1,
    faction: '2',
    isArchived: 0,
    hasDiscount: 0,
    quality: '4',
    modelPath: 'characters/models/hlym/choi/choi_prefab.vmdl',
    previewUrl: 'https://hlymmodelslist.oss-cn-beijing.aliyuncs.com/models/CT/choi_v2.png',
    previewOnline: {
      type: 'Buffer',
      data: [0],
    },
    previewType: '2',
    modelType: '0',
    tags: ['捐赠', '普通', 'hlym转模'],
  },
]
